openapi: 3.0.1
info:
  title: API de Gestión de Infraestructura en la Nube
  version: '1.0'
paths:
  /api/auth/register:
    post:
      summary: Registra un nuevo usuario
      tags:
        - Autenticación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistroUsuario'
      responses:
        '201':
          description: Usuario creado exitosamente
        '400':
          description: Error de validación
components:
  schemas:
    RegistroUsuario:
      type: object
      properties:
        nombre:
          type: string
        email:
          type: string
          format: email
        contraseña:
          type: string
          format: password
        rol:
          type: string
          enum:
            - Administrador
            - Operador
      required:
        - nombre
        - email
        - contraseña
        - rol
